// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiV2wnoyX5L8-aRLD3WyIDuqQbtPzhxyw',
    appId: '1:119038023555:web:e573dab1ce48324bf848b6',
    messagingSenderId: '119038023555',
    projectId: 'todolistapp-979b7',
    authDomain: 'todolistapp-979b7.firebaseapp.com',
    databaseURL: 'https://todolistapp-979b7-default-rtdb.firebaseio.com',
    storageBucket: 'todolistapp-979b7.appspot.com',
    measurementId: 'G-SK0V0P0E21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JfzmydgSBvrsvuAO2s-gZEw42F3EoO8',
    appId: '1:119038023555:android:0e78f9475a000a37f848b6',
    messagingSenderId: '119038023555',
    projectId: 'todolistapp-979b7',
    databaseURL: 'https://todolistapp-979b7-default-rtdb.firebaseio.com',
    storageBucket: 'todolistapp-979b7.appspot.com',
  );
}
